import {describe, expect, test} from 'bun:test';
import type {CodegenConfig} from '../../src/config/schema.js';
import {generateBase} from '../../src/codegen/base.js';

const defaultConfig: CodegenConfig = {
  dateType: 'string',
  enumType: 'constObject',
  propertyNameStyle: 'original',
  nullableType: 'null',
};

describe('generateBase', () => {
  test('generates BaseClient class by default', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('export class BaseClient {');
    expect(result).toContain('protected config: ApiConfig;');
    expect(result).toContain('protected async request<T>(');
  });

  test('generates BaseApi class when clientSuffix is Api', () => {
    const config: CodegenConfig = {...defaultConfig, clientSuffix: 'Api'};
    const result = generateBase(config);

    expect(result).toContain('export class BaseApi {');
    expect(result).not.toContain('BaseClient');
  });

  test('generates ApiConfig interface', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('export interface ApiConfig {');
    expect(result).toContain('baseUrl: string;');
    expect(result).toContain('headers?: Record<string, string>;');
  });

  test('generates ApiError class', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('export class ApiError extends Error {');
    expect(result).toContain('status: number;');
    expect(result).toContain('statusText: string;');
    expect(result).toContain('body?: unknown;');
  });

  test('request method handles query parameters', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('query?: Record<string, unknown>;');
    expect(result).toContain('url.searchParams.set(key, String(value))');
  });

  test('request method handles body', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('body?: unknown;');
    expect(result).toContain('JSON.stringify(options.body)');
    expect(result).toContain("headers['Content-Type'] = 'application/json'");
  });

  test('request method throws ApiError on non-2xx', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('if (!response.ok) {');
    expect(result).toContain('throw new ApiError(response.status, response.statusText, body);');
  });

  test('request method handles 204 No Content', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('if (response.status === 204) {');
    expect(result).toContain('return undefined as T;');
  });

  test('includes generated header comment', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('// Generated by OpenCodegen - do not edit manually');
  });

  test('generates HeadersInit type for dynamic headers', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('export type HeadersInit =');
    expect(result).toContain('| Record<string, string>');
    expect(result).toContain('| (() => Record<string, string>)');
    expect(result).toContain('| (() => Promise<Record<string, string>>)');
  });

  test('ApiConfig uses HeadersInit type', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain('headers?: HeadersInit;');
  });

  test('request method resolves dynamic headers', () => {
    const result = generateBase(defaultConfig);

    expect(result).toContain("typeof this.config.headers === 'function'");
    expect(result).toContain('await this.config.headers()');
  });
});
