import {mkdir, writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import type {OpenAPIV3} from 'openapi-types';
import type {OpenCodegenConfig} from '../config/schema.js';
import {generateBase} from './base.js';
import {generateClients, getClientClassNames, getClientFileNames} from './clients.js';
import {generateTypes} from './types.js';

export {generateTypes} from './types.js';
export {generateBase} from './base.js';
export {generateClients} from './clients.js';

/**
 * Map of filename to generated content.
 */
export type GeneratedFiles = Map<string, string>;

/**
 * Apply default values to codegen config.
 */
const applyCodegenDefaults = (config: OpenCodegenConfig['codegen']): Required<OpenCodegenConfig['codegen']> => ({
  dateType: config.dateType ?? 'string',
  enumType: config.enumType ?? 'constObject',
  propertyNameStyle: config.propertyNameStyle ?? 'original',
  nullableType: config.nullableType ?? 'null',
  methodNameStyle: config.methodNameStyle ?? 'operationId',
  clientSuffix: config.clientSuffix ?? 'Client',
});

/**
 * Generate the index.ts file with re-exports.
 */
const generateIndex = (doc: OpenAPIV3.Document, config: Required<OpenCodegenConfig['codegen']>): string => {
  const clientFileNames = getClientFileNames(doc);
  const clientClassNames = getClientClassNames(doc, config);

  const lines: string[] = [
    '// Generated by OpenCodegen - do not edit manually',
    '',
    "export * from './types.js';",
    "export { ApiConfig, ApiError, Base" + config.clientSuffix + " } from './base.js';",
  ];

  // Export each client
  for (let i = 0; i < clientFileNames.length; i++) {
    const fileName = clientFileNames[i];
    const className = clientClassNames[i];
    lines.push(`export { ${className} } from './${fileName}.js';`);
  }

  lines.push('');

  return lines.join('\n');
};

/**
 * Generate all code files from an OpenAPI document.
 * Returns a map of filename to content.
 */
export const generateCode = (doc: OpenAPIV3.Document, config: OpenCodegenConfig): GeneratedFiles => {
  const files: GeneratedFiles = new Map();
  const fullConfig = applyCodegenDefaults(config.codegen);

  // Generate types
  const typesContent = generateTypes(doc, config.codegen);
  files.set('types.ts', typesContent);

  // Generate base client
  const baseContent = generateBase(fullConfig);
  files.set('base.ts', baseContent);

  // Generate client classes
  const clientFiles = generateClients(doc, fullConfig);
  for (const [fileName, content] of clientFiles) {
    files.set(fileName, content);
  }

  // Generate index.ts
  const indexContent = generateIndex(doc, fullConfig);
  files.set('index.ts', indexContent);

  return files;
};

/**
 * Write generated files to the target directory.
 * Creates the directory if it doesn't exist.
 */
export const writeGeneratedFiles = async (files: GeneratedFiles, targetDir: string): Promise<void> => {
  // Ensure target directory exists
  await mkdir(targetDir, {recursive: true});

  // Write each file
  for (const [filename, content] of files) {
    const filePath = join(targetDir, filename);
    await writeFile(filePath, content, 'utf-8');
  }
};
